language: python

python:
  - "2.7"

services: postgresql

install: "pip install -r requirements.txt"

before_script:
  - psql -c "CREATE DATABASE bitly;" -U postgres
  - psql -c "CREATE USER demo WITH PASSWORD 'demo'"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE "bitly" to demo"

script: py.test src

