# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, unique=True, verbose_name=b'Enlace original')),
                ('slug', models.CharField(max_length=10, unique=True, verbose_name=b'Fragmento de URL corta')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
