# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(blank=True, max_length=10, verbose_name=b'Fragmento de URL corta'),
        ),
    ]
